#!/bin/bash
# demo.sh - Demonstration simulation of the banking system
#
# Since GnuCOBOL may not be available in all environments,
# this script simulates the system behavior for demonstration purposes.

echo "=============================================="
echo "    MINI CORE BANKING SYSTEM - DEMO"
echo "    Terminal-Based Core Banking"
echo "=============================================="
echo ""
echo "DISCLAIMER:"
echo "This is a demonstration simulation."
echo "The full implementation includes:"
echo "  - File-based persistence"
echo "  - Complete transaction ledger"
echo "  - Validation and business rules"
echo "  - Multi-account management"
echo ""
echo "All COBOL source code is available in src/"
echo ""
echo "Press ENTER to start demo..."
read

clear

echo "=== MAIN MENU ==="
echo ""
echo "  1 - Load Account"
echo "  2 - Create New Account"
echo "  9 - Exit"
echo ""
echo "Simulating: Create new account..."
sleep 1
echo ""
echo "CREATE NEW ACCOUNT"
echo "------------------"
echo ""
echo "Enter holder name: Alice Demo"
echo ""
sleep 1
echo "Account created successfully!"
echo "Account ID: 10000001"
echo ""
echo "Press ENTER to continue..."
read

clear

echo "=== MAIN MENU ==="
echo ""
echo "Simulating: Load account 10000001..."
sleep 1
echo ""
echo "Account loaded successfully."
echo ""
echo "Press ENTER to continue..."
read

clear

echo "=== OPERATIONS MENU ==="
echo ""
echo "Account ID:      10000001"
echo "Holder:          Alice Demo"
echo "Status:          ACTIVE"
echo "Balance:      R$       0.00"
echo "Blocked:      R$       0.00"
echo "Available:    R$       0.00"
echo ""
echo "  1 - Credit Account"
echo "  2 - Debit Account"
echo "  3 - Block Funds"
echo "  4 - View Ledger"
echo "  5 - Back to Main Menu"
echo ""
echo "Simulating: Credit R$ 1,000.00..."
sleep 1
echo ""
echo "=== CREDIT ACCOUNT ==="
echo ""
echo "Enter amount: 1000.00"
echo "Enter description: Initial deposit"
echo ""
sleep 1
echo "Credit processed successfully!"
echo "Transaction ID: 100000000001"
echo ""
echo "Press ENTER to continue..."
read

clear

echo "=== OPERATIONS MENU ==="
echo ""
echo "Account ID:      10000001"
echo "Holder:          Alice Demo"
echo "Status:          ACTIVE"
echo "Balance:      R$   1,000.00"
echo "Blocked:      R$       0.00"
echo "Available:    R$   1,000.00"
echo ""
echo "  1 - Credit Account"
echo "  2 - Debit Account"
echo "  3 - Block Funds"
echo "  4 - View Ledger"
echo "  5 - Back to Main Menu"
echo ""
echo "Simulating: Debit R$ 250.00..."
sleep 1
echo ""
echo "=== DEBIT ACCOUNT ==="
echo ""
echo "Enter amount: 250.00"
echo "Enter description: ATM withdrawal"
echo ""
sleep 1
echo "Debit processed successfully!"
echo "Transaction ID: 100000000002"
echo ""
echo "Press ENTER to continue..."
read

clear

echo "=== OPERATIONS MENU ==="
echo ""
echo "Account ID:      10000001"
echo "Holder:          Alice Demo"
echo "Status:          ACTIVE"
echo "Balance:      R$     750.00"
echo "Blocked:      R$       0.00"
echo "Available:    R$     750.00"
echo ""
echo "  1 - Credit Account"
echo "  2 - Debit Account"
echo "  3 - Block Funds"
echo "  4 - View Ledger"
echo "  5 - Back to Main Menu"
echo ""
echo "Simulating: Block R$ 100.00..."
sleep 1
echo ""
echo "=== BLOCK FUNDS ==="
echo ""
echo "Enter amount to block: 100.00"
echo "Enter description: Hotel authorization"
echo ""
sleep 1
echo "Funds blocked successfully!"
echo "Transaction ID: 100000000003"
echo ""
echo "Press ENTER to continue..."
read

clear

echo "=== OPERATIONS MENU ==="
echo ""
echo "Account ID:      10000001"
echo "Holder:          Alice Demo"
echo "Status:          ACTIVE"
echo "Balance:      R$     750.00"
echo "Blocked:      R$     100.00"
echo "Available:    R$     650.00"
echo ""
echo "Notice how:"
echo "  - Balance stays at R$ 750.00"
echo "  - Blocked increased to R$ 100.00"
echo "  - Available decreased to R$ 650.00"
echo ""
echo "This demonstrates the difference between:"
echo "  - Ledger Balance (total in account)"
echo "  - Available Balance (what can be withdrawn)"
echo ""
echo "Press ENTER to continue..."
read

clear

echo "=== TRANSACTION LEDGER (SIMULATED) ==="
echo ""
echo "Ledger for Account 10000001:"
echo "----------------------------------------------------------------------"
echo "ID          | Timestamp      | Type    | Amount    | Balance After"
echo "----------------------------------------------------------------------"
echo "1000000001  | 20260113143000 | CREDIT  | +1000.00  | 1000.00"
echo "1000000002  | 20260113143030 | DEBIT   |  -250.00  |  750.00"
echo "1000000003  | 20260113143100 | BLOCK   |  -100.00* |  750.00"
echo "----------------------------------------------------------------------"
echo ""
echo "* BLOCK doesn't change ledger balance, only available balance"
echo ""
echo "Key Points:"
echo "  - Ledger is immutable (append-only)"
echo "  - Every operation is recorded"
echo "  - Balance transitions are tracked"
echo "  - Timestamp provides audit trail"
echo ""
echo "Press ENTER to continue..."
read

clear

echo "=============================================="
echo "    DEMONSTRATION COMPLETE"
echo "=============================================="
echo ""
echo "What you just saw:"
echo ""
echo "1. Account Creation"
echo "   - Auto-generated ID (10000001)"
echo "   - Initial balance R$ 0.00"
echo ""
echo "2. Credit Operation"
echo "   - Deposited R$ 1,000.00"
echo "   - Balance increased"
echo ""
echo "3. Debit Operation"
echo "   - Withdrew R$ 250.00"
echo "   - Balance decreased"
echo "   - Validates sufficient funds"
echo ""
echo "4. Block Operation"
echo "   - Blocked R$ 100.00"
echo "   - Balance unchanged"
echo "   - Available balance reduced"
echo ""
echo "5. Ledger View"
echo "   - Immutable transaction log"
echo "   - Complete audit trail"
echo ""
echo "=============================================="
echo ""
echo "This simulation demonstrates the core concepts."
echo "The actual implementation includes:"
echo ""
echo "  ✓ COBOL source code (src/)"
echo "  ✓ File-based persistence"
echo "  ✓ Transaction processing"
echo "  ✓ Business rule validation"
echo "  ✓ Indexed file access"
echo "  ✓ Sequential ledger logging"
echo ""
echo "To build and run the real system:"
echo "  1. Install GnuCOBOL"
echo "  2. Run ./build.sh"
echo "  3. Run ./run.sh"
echo ""
echo "See README.md for details."
echo ""
echo "=============================================="
echo "    Thank you for reviewing this project"
echo "=============================================="
